In [1]:
import scanpy as sc

In [2]:
!pwd

/home/jovyan/work/code

In [3]:
adata = sc.read_h5ad("../data/Cell/counts.h5ad")
adata

AnnData object with n_obs × n_vars = 157932 × 12939

add sample source to annotation, fetal_adrenal_gland or tumor

In [6]:
# source_annotation_list = []
# for id in adata.obs_names:
#     if id[0] == "F":
#         source_annotation_list.append("fetal_adrenal_gland")
#     elif id[0] == "T":
#         source_annotation_list.append("tumor")
# print(source_annotation_list[:10])

['tumor', 'tumor', 'tumor', 'tumor', 'tumor', 'tumor', 'tumor', 'tumor', 'tumor', 'tumor']

In [7]:
# adata.obs["sample_source"] = source_annotation_list
# adata.obs[["sample_source"]]

                       sample_source
Cell_barcode
T44_AAACCTGAGAGGTTGC.1         tumor
T44_AAACCTGAGAGTGAGA.1         tumor
T44_AAACCTGAGGCATGTG.1         tumor
T44_AAACCTGAGTGTACCT.1         tumor
T44_AAACCTGCAATGCCAT.1         tumor
...                              ...
T40_TTTGTCAGTGTCCTCT.1         tumor
T40_TTTGTCATCACTTATC.1         tumor
T40_TTTGTCATCAGGCCCA.1         tumor
T40_TTTGTCATCTGCAGTA.1         tumor
T40_TTTGTCATCTGGAGCC.1         tumor

[203503 rows x 1 columns]

add patient ID annotation

In [4]:
id_annotation_list = []
for barcode in adata.obs_names:
    id = barcode.split("_")[0]
    id_annotation_list.append(id)

In [5]:
adata.obs["sample_ID"] = id_annotation_list
adata.obs[["sample_ID"]]

                       sample_ID
Cell_barcode
T44_AAACCTGAGAGGTTGC.1       T44
T44_AAACCTGAGAGTGAGA.1       T44
T44_AAACCTGAGGCATGTG.1       T44
T44_AAACCTGAGTGTACCT.1       T44
T44_AAACCTGCAATGCCAT.1       T44
...                          ...
T40_TTTGTCAGTGTCCTCT.1       T40
T40_TTTGTCATCACTTATC.1       T40
T40_TTTGTCATCAGGCCCA.1       T40
T40_TTTGTCATCTGCAGTA.1       T40
T40_TTTGTCATCTGGAGCC.1       T40

[157932 rows x 1 columns]

In [16]:
male_ids = ["T10", "T27", "T40", "T69", "T71", "T162", "T175", "T188", "T230"]
female_ids = ["T19", "T34", "T44", "T75", "T92", "T200", "T214"]

In [18]:
gender_annotation_list = []
# male = ["T10", "T27", "T40", "T69", "T71", "T162", "T174", "T188", "T230"]  # we do not include T10 in our dataset
for i in adata.obs["sample_ID"]:
    if i[0] == 'F':
        gender_annotation_list.append("NA")
    elif i in male_ids:
        gender_annotation_list.append("M")
    else:
        gender_annotation_list.append("F")

print(gender_annotation_list[:10])

['F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F']

In [19]:
adata.obs["Gender"] = gender_annotation_list
adata.obs["Gender"]

Cell_barcode
T44_AAACCTGAGAGGTTGC.1    F
T44_AAACCTGAGAGTGAGA.1    F
T44_AAACCTGAGGCATGTG.1    F
T44_AAACCTGAGTGTACCT.1    F
T44_AAACCTGCAATGCCAT.1    F
                         ..
T40_TTTGTCAGTGTCCTCT.1    M
T40_TTTGTCATCACTTATC.1    M
T40_TTTGTCATCAGGCCCA.1    M
T40_TTTGTCATCTGCAGTA.1    M
T40_TTTGTCATCTGGAGCC.1    M
Name: Gender, Length: 157932, dtype: object

In [20]:
stage1 = ["T44", "T175", "T188"]
stage3 = ["T19", "T200", "T214", "T230"]
stage4 = ["T10", "T27", "T34", "T40", "T69", "T75", "T92", "T162"]
stage4S = ["T71"]

In [21]:
INSS_annotation_list = []
for i in adata.obs["sample_ID"]:
    if i in stage1:
        INSS_annotation_list.append("I")
    elif i in stage3:
        INSS_annotation_list.append("III")
    elif i in stage4:
        INSS_annotation_list.append("IV")
    elif i in stage4S:
        INSS_annotation_list.append("4S")
    else:
        INSS_annotation_list.append("NA")
        
print(INSS_annotation_list[:10])

['I', 'I', 'I', 'I', 'I', 'I', 'I', 'I', 'I', 'I']

In [22]:
adata.obs["INSS_stage"] = INSS_annotation_list
adata.obs["INSS_stage"]

Cell_barcode
T44_AAACCTGAGAGGTTGC.1     I
T44_AAACCTGAGAGTGAGA.1     I
T44_AAACCTGAGGCATGTG.1     I
T44_AAACCTGAGTGTACCT.1     I
T44_AAACCTGCAATGCCAT.1     I
                          ..
T40_TTTGTCAGTGTCCTCT.1    IV
T40_TTTGTCATCACTTATC.1    IV
T40_TTTGTCATCAGGCCCA.1    IV
T40_TTTGTCATCTGCAGTA.1    IV
T40_TTTGTCATCTGGAGCC.1    IV
Name: INSS_stage, Length: 157932, dtype: object

In [23]:
adata

AnnData object with n_obs × n_vars = 157932 × 12939
    obs: 'sample_ID', 'Gender', 'INSS_stage'

In [24]:
%pwd
%cd /home/jovyan/work/results/Cell/
%pwd

/home/jovyan/work/results/Cell

'/home/jovyan/work/results/Cell'

In [25]:
adata.write("annotated.h5ad")