In [1]:
%pwd
%cd /home/jovyan/work/results/Cell/
%pwd

/home/jovyan/work/results/Cell

'/home/jovyan/work/results/Cell'

In [2]:
import scanpy as sc
import pandas as pd

In [3]:
adata = sc.read_h5ad("NE_reclustered.h5ad")
adata

AnnData object with n_obs × n_vars = 115774 × 12939
    obs: 'sample_ID', 'Gender', 'INSS_stage', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'doublet_score', 'predicted_doublet', 'cell_type', '_scvi_batch', '_scvi_labels', 'leiden_scVI'
    var: 'n_cells', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'highly_variable', 'highly_variable_rank', 'means', 'variances', 'variances_norm', 'highly_variable_nbatches'
    uns: 'INSS_stage_colors', '_scvi_manager_uuid', '_scvi_uuid', 'hvg', 'leiden_scVI', 'leiden_scVI_colors', 'leiden_scVI_sizes', 'neighbors', 'paga', 'sample_ID_colors', 'scrublet', 'umap'
    obsm: 'X_scVI', 'X_umap', '_scvi_extra_continuous_covs'
    layers: 'scvi_normalized'
    obsp: 'connectivities', 'distances'

In [4]:
adata.obs.leiden_scVI

Cell_barcode
T44_AAACCTGAGAGGTTGC.1     2
T44_AAACCTGAGAGTGAGA.1     2
T44_AAACCTGAGGCATGTG.1     2
T44_AAACCTGAGTGTACCT.1    48
T44_AAACCTGCAATGCCAT.1     2
                          ..
T40_TTTGGTTAGCAATATG.1     7
T40_TTTGGTTAGTGGAGTC.1    24
T40_TTTGGTTCATAGTAAG.1    12
T40_TTTGTCAAGTCAATAG.1     7
T40_TTTGTCATCACTTATC.1    17
Name: leiden_scVI, Length: 115774, dtype: category
Categories (56, object): ['0', '1', '2', '3', ..., '52', '53', '54', '55']

In [5]:
adata.obs[["leiden_scVI"]].value_counts()

leiden_scVI
0              5235
1              4394
2              4370
3              4097
4              4055
5              3772
6              3715
7              3628
8              3289
9              3272
10             3212
11             3188
12             3073
13             2925
14             2863
15             2784
16             2781
17             2761
18             2416
19             2407
20             2388
21             2364
22             2261
23             2205
24             2123
25             2037
26             2023
27             1912
28             1827
29             1749
30             1733
31             1665
32             1551
33             1544
34             1513
35             1435
36             1416
37             1387
38             1286
39             1240
40             1204
41             1185
42             1143
43             1127
44             1037
45              979
46              896
47              827
48              738
49              627
50              609
51              535
52              459
53              414
54               74
55               24
Name: count, dtype: int64

In [6]:
adata.obs["INSS_stage"]

Cell_barcode
T44_AAACCTGAGAGGTTGC.1     I
T44_AAACCTGAGAGTGAGA.1     I
T44_AAACCTGAGGCATGTG.1     I
T44_AAACCTGAGTGTACCT.1     I
T44_AAACCTGCAATGCCAT.1     I
                          ..
T40_TTTGGTTAGCAATATG.1    IV
T40_TTTGGTTAGTGGAGTC.1    IV
T40_TTTGGTTCATAGTAAG.1    IV
T40_TTTGTCAAGTCAATAG.1    IV
T40_TTTGTCATCACTTATC.1    IV
Name: INSS_stage, Length: 115774, dtype: category
Categories (4, object): ['4S', 'I', 'III', 'IV']

start to annotate each leiden cluster with a cancer stage

In [7]:
# just take a look
adata[(adata.obs.leiden_scVI == '0') & (adata.obs.INSS_stage == 'IV')].n_obs

4926

In [8]:
data = {'4S': [adata[(adata.obs.leiden_scVI == str(i)) & (adata.obs.INSS_stage == '4S')].n_obs for i in range(len(adata.obs[["leiden_scVI"]].value_counts()))],
        'I': [adata[(adata.obs.leiden_scVI == str(i)) & (adata.obs.INSS_stage == 'I')].n_obs for i in range(len(adata.obs[["leiden_scVI"]].value_counts()))], 
        'III': [adata[(adata.obs.leiden_scVI == str(i)) & (adata.obs.INSS_stage == 'III')].n_obs for i in range(len(adata.obs[["leiden_scVI"]].value_counts()))],
        'IV': [adata[(adata.obs.leiden_scVI == str(i)) & (adata.obs.INSS_stage == 'IV')].n_obs for i in range(len(adata.obs[["leiden_scVI"]].value_counts()))],
        #'NA': [adata[(adata.obs.metacell == i) & (adata.obs.INSS_stage == 'NA')].n_obs for i in range(len(adata.obs[["metacell"]].value_counts()))]
       }

In [9]:
df = pd.DataFrame(data)
df.index.name = 'leiden'
df

          4S     I   III    IV
leiden
0         17    55   237  4926
1         15     7    50  4322
2        488  3256     6   620
3          0     2   175  3920
4         50  3571   211   223
5        140   442    48  3142
6         92  2871   644   108
7        786  1455  1009   378
8        114  2825   259    91
9          0    15  3218    39
10       358  1068    11  1775
11         4    18   133  3033
12       252   282    16  2523
13      1948   319    28   630
14         0     0    82  2781
15         2    14  2723    45
16       131  1473  1042   135
17      2110   196    31   424
18       138  2133   118    27
19       137   159     6  2105
20      1714   278    78   318
21         0     0  2200   164
22         0     2  2249    10
23         4   292  1894    15
24       182   585  1163   193
25         5     3     1  2028
26        39   156  1802    26
27         0     3  1897    12
28         8    32   158  1629
29         4    30   182  1533
30        34   223   219  1257
31        20  1463   147    35
32        43   187     4  1317
33       111    62    27  1344
34         0     1  1489    23
35         0     0  1427     8
36         0     2    67  1347
37        11    72    72  1232
38         2     0    11  1273
39        12     4    33  1191
40         1     6  1170    27
41         1  1088    84    12
42        15    11    58  1059
43         6   575   334   212
44       252   190   243   352
45         0     0   968    11
46       115   545   172    64
47         1     4   798    24
48        26   341    19   352
49        17   576    20    14
50        59     2    22   526
51         2   371   155     7
52         0     0   451     8
53         1     3    22   388
54         0    56    10     8
55         0     0    21     3

now normalized along each column

In [10]:
normalized_df=(df-df.min())/(df.max()-df.min())
normalized_df

              4S         I       III        IV
leiden
0       0.008057  0.015402  0.073360  1.000000
1       0.007109  0.001960  0.015232  0.877311
2       0.231280  0.911789  0.001554  0.125330
3       0.000000  0.000560  0.054088  0.795653
4       0.023697  1.000000  0.065278  0.044688
5       0.066351  0.123775  0.014610  0.637619
6       0.043602  0.803976  0.199876  0.021328
7       0.372512  0.407449  0.313335  0.076173
8       0.054028  0.791095  0.080199  0.017875
9       0.000000  0.004201  1.000000  0.007313
10      0.169668  0.299076  0.003108  0.359943
11      0.001896  0.005041  0.041032  0.615478
12      0.119431  0.078969  0.004663  0.511883
13      0.923223  0.089331  0.008393  0.127361
14      0.000000  0.000000  0.025179  0.564290
15      0.000948  0.003920  0.846130  0.008531
16      0.062085  0.412489  0.323593  0.026813
17      1.000000  0.054887  0.009325  0.085517
18      0.065403  0.597312  0.036369  0.004875
19      0.064929  0.044525  0.001554  0.426975
20      0.812322  0.077849  0.023935  0.063985
21      0.000000  0.000000  0.683556  0.032704
22      0.000000  0.000560  0.698788  0.001422
23      0.001896  0.081770  0.588436  0.002438
24      0.086256  0.163820  0.361206  0.038594
25      0.002370  0.000840  0.000000  0.411335
26      0.018483  0.043685  0.559838  0.004672
27      0.000000  0.000840  0.589369  0.001828
28      0.003791  0.008961  0.048803  0.330286
29      0.001896  0.008401  0.056264  0.310786
30      0.016114  0.062447  0.067765  0.254723
31      0.009479  0.409689  0.045384  0.006500
32      0.020379  0.052366  0.000933  0.266910
33      0.052607  0.017362  0.008082  0.272395
34      0.000000  0.000280  0.462543  0.004063
35      0.000000  0.000000  0.443270  0.001016
36      0.000000  0.000560  0.020516  0.273004
37      0.005213  0.020162  0.022070  0.249645
38      0.000948  0.000000  0.003108  0.257973
39      0.005687  0.001120  0.009947  0.241316
40      0.000474  0.001680  0.363382  0.004875
41      0.000474  0.304677  0.025800  0.001828
42      0.007109  0.003080  0.017718  0.214503
43      0.002844  0.161019  0.103513  0.042454
44      0.119431  0.053206  0.075225  0.070892
45      0.000000  0.000000  0.300591  0.001625
46      0.054502  0.152618  0.053155  0.012391
47      0.000474  0.001120  0.247746  0.004266
48      0.012322  0.095491  0.005595  0.070892
49      0.008057  0.161299  0.005906  0.002234
50      0.027962  0.000560  0.006528  0.106236
51      0.000948  0.103892  0.047871  0.000813
52      0.000000  0.000000  0.139882  0.001016
53      0.000474  0.000840  0.006528  0.078204
54      0.000000  0.015682  0.002798  0.001016
55      0.000000  0.000000  0.006217  0.000000

In [11]:
normalized_df.to_csv("NE_normalized_stages.csv")

In [12]:
cluster_stages = normalized_df.idxmax(axis=1)
cluster_stages.name = "discrete_cancer_stage"
cluster_stages

leiden
0      IV
1      IV
2       I
3      IV
4       I
5      IV
6       I
7       I
8       I
9     III
10     IV
11     IV
12     IV
13     4S
14     IV
15    III
16      I
17     4S
18      I
19     IV
20     4S
21    III
22    III
23    III
24    III
25     IV
26    III
27    III
28     IV
29     IV
30     IV
31      I
32     IV
33     IV
34    III
35    III
36     IV
37     IV
38     IV
39     IV
40    III
41      I
42     IV
43      I
44     4S
45    III
46      I
47    III
48      I
49      I
50     IV
51      I
52    III
53     IV
54      I
55    III
Name: discrete_cancer_stage, dtype: object

In [13]:
cluster_stages.to_csv("NE_cluster_stages.csv")