In [1]:
import pandas as pd
import glob
import gc  # for memory clearup

In [2]:
!pwd

/home/jovyan/work/code

In [5]:
input_path = "../data/Cell/NB/"

files = glob.glob(input_path + "*.csv")
print(files)  # use the string slicing method to get the T.. information?

tumor_list = [file_name.split("_")[-5] for file_name in files]
print(tumor_list)

['../data/Cell/NB/GSM4654669_T162_gene_cell_exprs_table.csv', '../data/Cell/NB/GSM4088782_T75_gene_cell_exprs_table.csv', '../data/Cell/NB/GSM4654672_T200_gene_cell_exprs_table.csv', '../data/Cell/NB/GSM4088776_T27_gene_cell_exprs_table.csv', '../data/Cell/NB/GSM4088778_T40_gene_cell_exprs_table.csv', '../data/Cell/NB/GSM4654674_T230_gene_cell_exprs_table.csv', '../data/Cell/NB/GSM4654673_T214_gene_cell_exprs_table.csv', '../data/Cell/NB/GSM4088779_T44_gene_cell_exprs_table.csv', '../data/Cell/NB/GSM4088783_T92_gene_cell_exprs_table.csv', '../data/Cell/NB/GSM4654671_T188_gene_cell_exprs_table.csv', '../data/Cell/NB/GSM4088777_T34_gene_cell_exprs_table.csv', '../data/Cell/NB/GSM4088781_T71_gene_cell_exprs_table.csv', '../data/Cell/NB/GSM4088780_T69_gene_cell_exprs_table.csv', '../data/Cell/NB/GSM4654670_T175_gene_cell_exprs_table.csv']
['T162', 'T75', 'T200', 'T27', 'T40', 'T230', 'T214', 'T44', 'T92', 'T188', 'T34', 'T71', 'T69', 'T175']

In [6]:
pd_dataframe_list = []
for file in files:
    df = pd.read_csv(file)
    sliced = df.loc[:, df.columns!="Gene_ID"]
    pd_dataframe_list.append(sliced)
    

del files
gc.collect()

0

after deleting "Gene_ID" from some files, prefix all columns' names with tumor_id_ except the "Symbol" column

In [7]:
# tumor_list = ["T27", "T34", "T40", "T44", "T69", "T71", "T75", "T92", "T162", "T174", "T188", "T200", "T214", "T230", "F2", "F7", "F106", "F107"]  # it also includes fetal adrenal glands
# the order of tumor_list needs to consider the file order in the folder
for i in range(len(tumor_list)):
    pd_dataframe_list[i] = pd_dataframe_list[i].add_prefix(tumor_list[i]+"_")
    pd_dataframe_list[i].rename(columns={tumor_list[i]+"_Symbol": "Symbol"}, inplace=True)
    
for df in pd_dataframe_list:
    print(df.columns)

Index(['Symbol', 'T162_AAACCCAAGACCATTC.1', 'T162_AAACCCAAGATCCAAA.1',
       'T162_AAACCCAAGATGAAGG.1', 'T162_AAACCCAAGCAAACAT.1',
       'T162_AAACCCAAGCACAAAT.1', 'T162_AAACCCAAGCACTTTG.1',
       'T162_AAACCCAAGCTCCACG.1', 'T162_AAACCCAAGGCAGGGA.1',
       'T162_AAACCCAAGGCATGGT.1',
       ...
       'T162_GCCGATGTCGTTCCTG.1', 'T162_GCCGATGTCTAGACAC.1',
       'T162_GCCGATGTCTCGACCT.1', 'T162_GCCGTGAAGAAGGCTC.1',
       'T162_GCCGTGAAGCCAACCC.1', 'T162_GCCGTGAAGGTAATCA.1',
       'T162_GCCGTGAAGTGGACTG.1', 'T162_GCCGTGACAAGCGCAA.1',
       'T162_GCCGTGACACCCTGAG.1', 'T162_GCCGTGACACGAAGAC.1'],
      dtype='object', length=16385)
Index(['Symbol', 'T75_AAACCTGAGATCCCAT.1', 'T75_AAACCTGAGCCTTGAT.1',
       'T75_AAACCTGAGCGATAGC.1', 'T75_AAACCTGAGCGTTTAC.1',
       'T75_AAACCTGAGGAATGGA.1', 'T75_AAACCTGAGGAGTCTG.1',
       'T75_AAACCTGAGTACTTGC.1', 'T75_AAACCTGCAACTGCTA.1',
       'T75_AAACCTGCAAGAGGCT.1',
       ...
       'T75_TTTGGTTAGGACACCA.1', 'T75_TTTGGTTAGGAGTTTA.1',
       'T75_TTTGGTTAGGGCTCTC.1', 'T75_TTTGGTTAGTACGTAA.1',
       'T75_TTTGGTTAGTGGTAAT.1', 'T75_TTTGGTTAGTTGAGAT.1',
       'T75_TTTGGTTCAAGCGATG.1', 'T75_TTTGGTTCAATCGGTT.1',
       'T75_TTTGGTTCACCTCGTT.1', 'T75_TTTGGTTCACCTGGTG.1'],
      dtype='object', length=16383)
Index(['Symbol', 'T200_AAACCCAAGATACATG.1', 'T200_AAACCCAAGATGGGCT.1',
       'T200_AAACCCAAGCGTTAGG.1', 'T200_AAACCCAAGGTAGCAC.1',
       'T200_AAACCCAAGGTCACAG.1', 'T200_AAACCCAAGTTCATCG.1',
       'T200_AAACCCACAACAAGAT.1', 'T200_AAACCCACACCCAAGC.1',
       'T200_AAACCCACACCTATCC.1',
       ...
       'T200_TTTGTTGCAGTCGCTG.1', 'T200_TTTGTTGGTACACTCA.1',
       'T200_TTTGTTGGTATCGCGC.1', 'T200_TTTGTTGGTCGCGTCA.1',
       'T200_TTTGTTGGTGGACCAA.1', 'T200_TTTGTTGGTGTCCCTT.1',
       'T200_TTTGTTGGTTGCCTAA.1', 'T200_TTTGTTGTCGAACGCC.1',
       'T200_TTTGTTGTCTCGCAGG.1', 'T200_Unnamed: 14467'],
      dtype='object', length=14468)
Index(['Symbol', 'T27_AAACCTGAGCACGCCT.1', 'T27_AAACCTGAGCGTCTAT.1',
       'T27_AAACCTGAGGTACTCT.1', 'T27_AAACCTGAGGTGCAAC.1',
       'T27_AAACCTGAGTTAAGTG.1', 'T27_AAACCTGCAACACCTA.1',
       'T27_AAACCTGGTAAATACG.1', 'T27_AAACCTGGTATCGCAT.1',
       'T27_AAACCTGGTCCATGAT.1',
       ...
       'T27_TTTGTCAAGATGCGAC.1', 'T27_TTTGTCAAGCGTGAAC.1',
       'T27_TTTGTCAAGGTGCTTT.1', 'T27_TTTGTCAAGTACATGA.1',
       'T27_TTTGTCACACAGCCCA.1', 'T27_TTTGTCAGTCGACTGC.1',
       'T27_TTTGTCAGTTTCGCTC.1', 'T27_TTTGTCATCCTTCAAT.1',
       'T27_TTTGTCATCGCCTGAG.1', 'T27_TTTGTCATCTCGAGTA.1'],
      dtype='object', length=6830)
Index(['Symbol', 'T40_AAACCTGAGAGGGCTT.1', 'T40_AAACCTGAGATGTGTA.1',
       'T40_AAACCTGAGCTCTCGG.1', 'T40_AAACCTGAGGATGCGT.1',
       'T40_AAACCTGAGGCACATG.1', 'T40_AAACCTGAGTGACTCT.1',
       'T40_AAACCTGCAAAGTGCG.1', 'T40_AAACCTGCAGTTCCCT.1',
       'T40_AAACCTGCATGAAGTA.1',
       ...
       'T40_TTTGTCACAGACAAGC.1', 'T40_TTTGTCACATGTTCCC.1',
       'T40_TTTGTCAGTCATTAGC.1', 'T40_TTTGTCAGTCGATTGT.1',
       'T40_TTTGTCAGTGAGCGAT.1', 'T40_TTTGTCAGTGTCCTCT.1',
       'T40_TTTGTCATCACTTATC.1', 'T40_TTTGTCATCAGGCCCA.1',
       'T40_TTTGTCATCTGCAGTA.1', 'T40_TTTGTCATCTGGAGCC.1'],
      dtype='object', length=6793)
Index(['Symbol', 'T230_AAACCCAAGAACCGCA.1', 'T230_AAACCCAAGACGAGCT.1',
       'T230_AAACCCACAATACCCA.1', 'T230_AAACCCACACAGTACT.1',
       'T230_AAACCCACACTGAATC.1', 'T230_AAACCCACAGATACCT.1',
       'T230_AAACCCACAGTTGAAA.1', 'T230_AAACCCAGTAGTCTTG.1',
       'T230_AAACCCAGTCTACGTA.1',
       ...
       'T230_TTTGTTGCATTACTCT.1', 'T230_TTTGTTGCATTGCTTT.1',
       'T230_TTTGTTGGTAACTTCG.1', 'T230_TTTGTTGGTACAGTAA.1',
       'T230_TTTGTTGGTACCTAAC.1', 'T230_TTTGTTGGTAGAGATT.1',
       'T230_TTTGTTGGTTTACCTT.1', 'T230_TTTGTTGTCTACACAG.1',
       'T230_TTTGTTGTCTCGTGAA.1', 'T230_Unnamed: 14529'],
      dtype='object', length=14530)
Index(['Symbol', 'T214_AAACCCAAGAAGTCTA.1', 'T214_AAACCCAAGCAACTTC.1',
       'T214_AAACCCAAGCCGTAAG.1', 'T214_AAACCCAAGCTAGAGC.1',
       'T214_AAACCCAAGCTGCCTG.1', 'T214_AAACCCAAGGGATCGT.1',
       'T214_AAACCCACAACCTAAC.1', 'T214_AAACCCACAAGTGATA.1',
       'T214_AAACCCAGTAGACGGT.1',
       ...
       'T214_TTTGTTGCAAATCGGG.1', 'T214_TTTGTTGCATTGTCGA.1',
       'T214_TTTGTTGGTAATCAAG.1', 'T214_TTTGTTGGTACGATTC.1',
       'T214_TTTGTTGGTATTGGCT.1', 'T214_TTTGTTGGTGAGACCA.1',
       'T214_TTTGTTGGTGGGTATG.1', 'T214_TTTGTTGTCATTTGTC.1',
       'T214_TTTGTTGTCTGGGTCG.1', 'T214_Unnamed: 10347'],
      dtype='object', length=10348)
Index(['Symbol', 'T44_AAACCTGAGAGGTTGC.1', 'T44_AAACCTGAGAGTGAGA.1',
       'T44_AAACCTGAGGCATGTG.1', 'T44_AAACCTGAGTGTACCT.1',
       'T44_AAACCTGCAATGCCAT.1', 'T44_AAACCTGCAATGGATA.1',
       'T44_AAACCTGCACTGTGTA.1', 'T44_AAACCTGGTAATCACC.1',
       'T44_AAACCTGGTAGTGAAT.1',
       ...
       'T44_TTTGTCAAGCCCTAAT.1', 'T44_TTTGTCAAGCGGCTTC.1',
       'T44_TTTGTCAAGGATGTAT.1', 'T44_TTTGTCAAGGTACTCT.1',
       'T44_TTTGTCAAGGTGTGGT.1', 'T44_TTTGTCACAAGCTGGA.1',
       'T44_TTTGTCAGTATCGCAT.1', 'T44_TTTGTCAGTTCAACCA.1',
       'T44_TTTGTCATCAGCACAT.1', 'T44_TTTGTCATCTCCAGGG.1'],
      dtype='object', length=6917)
Index(['Symbol', 'T92_AAACCTGAGCGTGAAC.1', 'T92_AAACCTGAGGGATCTG.1',
       'T92_AAACCTGCAAATCCGT.1', 'T92_AAACCTGCACACCGAC.1',
       'T92_AAACCTGTCAAGAAGT.1', 'T92_AAACCTGTCTTGTTTG.1',
       'T92_AAACGGGGTGACTCAT.1', 'T92_AAACGGGTCACCGTAA.1',
       'T92_AAAGATGAGAGGGCTT.1',
       ...
       'T92_TTTGTCAAGATACACA.1', 'T92_TTTGTCAAGCACAGGT.1',
       'T92_TTTGTCAAGCGTCAAG.1', 'T92_TTTGTCAAGCTGAACG.1',
       'T92_TTTGTCACATACCATG.1', 'T92_TTTGTCACATCGGACC.1',
       'T92_TTTGTCAGTCGAAAGC.1', 'T92_TTTGTCAGTGACTACT.1',
       'T92_TTTGTCATCCAAATGC.1', 'T92_TTTGTCATCTGCCAGG.1'],
      dtype='object', length=4243)
Index(['Symbol', 'T188_AAACCCACAAAGGTTA.1', 'T188_AAACCCACAGTTAGGG.1',
       'T188_AAACCCACATGAAGGC.1', 'T188_AAACCCAGTACTGACT.1',
       'T188_AAACCCAGTATCCCAA.1', 'T188_AAACCCAGTATGCGGA.1',
       'T188_AAACCCAGTCTGTAAC.1', 'T188_AAACCCAGTGTTTCTT.1',
       'T188_AAACCCAGTTCACCGG.1',
       ...
       'T188_TTTGTTGCATAATGCC.1', 'T188_TTTGTTGGTCACTAGT.1',
       'T188_TTTGTTGGTTCTCCAC.1', 'T188_TTTGTTGGTTCTGAGT.1',
       'T188_TTTGTTGGTTGTTGTG.1', 'T188_TTTGTTGTCATAGAGA.1',
       'T188_TTTGTTGTCATGCCGG.1', 'T188_TTTGTTGTCCACGAAT.1',
       'T188_TTTGTTGTCTGCTTAT.1', 'T188_Unnamed: 13570'],
      dtype='object', length=13571)
Index(['Symbol', 'T34_AAACCTGAGAAGGACA.1', 'T34_AAACCTGAGCCACCTG.1',
       'T34_AAACCTGAGTGCGATG.1', 'T34_AAACCTGGTTGATTGC.1',
       'T34_AAACCTGTCTCCTATA.1', 'T34_AAACGGGGTCAAGCGA.1',
       'T34_AAACGGGTCACCAGGC.1', 'T34_AAAGATGAGGAATTAC.1',
       'T34_AAAGATGCAGGATTGG.1',
       ...
       'T34_TTTGGTTCAAAGCGGT.1', 'T34_TTTGGTTCATGACATC.1',
       'T34_TTTGGTTGTACATCCA.1', 'T34_TTTGGTTTCTGCGGCA.1',
       'T34_TTTGTCACACCGCTAG.1', 'T34_TTTGTCACAGGATCGA.1',
       'T34_TTTGTCAGTACCTACA.1', 'T34_TTTGTCAGTTATCGGT.1',
       'T34_TTTGTCAGTTTACTCT.1', 'T34_TTTGTCATCTGGTTCC.1'],
      dtype='object', length=2573)
Index(['Symbol', 'T71_AAACCTGAGAAGGACA.1', 'T71_AAACCTGAGACGCTTT.1',
       'T71_AAACCTGAGATCCGAG.1', 'T71_AAACCTGAGATGCGAC.1',
       'T71_AAACCTGAGCAGCCTC.1', 'T71_AAACCTGAGCTCCTCT.1',
       'T71_AAACCTGAGTATTGGA.1', 'T71_AAACCTGAGTGGTAGC.1',
       'T71_AAACCTGAGTTGCAGG.1',
       ...
       'T71_TTTGTCACAGGGCATA.1', 'T71_TTTGTCACATTGGGCC.1',
       'T71_TTTGTCAGTAAACACA.1', 'T71_TTTGTCAGTACAGACG.1',
       'T71_TTTGTCAGTATAGGTA.1', 'T71_TTTGTCAGTCATATCG.1',
       'T71_TTTGTCAGTGTGTGCC.1', 'T71_TTTGTCAGTTAAGAAC.1',
       'T71_TTTGTCATCCCAACGG.1', 'T71_TTTGTCATCGCCAAAT.1'],
      dtype='object', length=12472)
Index(['Symbol', 'T69_AAACCTGAGACGCAAC.1', 'T69_AAACCTGAGACGCACA.1',
       'T69_AAACCTGAGACTACAA.1', 'T69_AAACCTGAGAGAGCTC.1',
       'T69_AAACCTGAGCAGACTG.1', 'T69_AAACCTGAGCCCGAAA.1',
       'T69_AAACCTGAGTACGCGA.1', 'T69_AAACCTGAGTATTGGA.1',
       'T69_AAACCTGCACAGGAGT.1',
       ...
       'T69_TTTGTCAGTAGAGTGC.1', 'T69_TTTGTCAGTCTCGTTC.1',
       'T69_TTTGTCAGTGCATCTA.1', 'T69_TTTGTCAGTGCTAGCC.1',
       'T69_TTTGTCATCAAGCCTA.1', 'T69_TTTGTCATCACATACG.1',
       'T69_TTTGTCATCCAAACTG.1', 'T69_TTTGTCATCCTGCAGG.1',
       'T69_TTTGTCATCGTTTATC.1', 'T69_TTTGTCATCTTACCTA.1'],
      dtype='object', length=16054)
Index(['Symbol', 'T175_AAACCCAAGAGTGTTA.1', 'T175_AAACCCAAGCCTGGAA.1',
       'T175_AAACCCAAGCGGACAT.1', 'T175_AAACCCAAGTCTGTAC.1',
       'T175_AAACCCACACAATGCT.1', 'T175_AAACCCACACGAGAAC.1',
       'T175_AAACCCACAGCTACCG.1', 'T175_AAACCCACATCACCAA.1',
       'T175_AAACCCACATCCTATT.1',
       ...
       'T175_TGTCCTGCACCTCTAC.1', 'T175_TGTCCTGCAGAATTCC.1',
       'T175_TGTCCTGCAGCTGAAG.1', 'T175_TGTCCTGCATCGGCCA.1',
       'T175_TGTCCTGCATTCGATG.1', 'T175_TGTCCTGCATTGCTGA.1',
       'T175_TGTCCTGGTAGTAAGT.1', 'T175_TGTCCTGGTATCATGC.1',
       'T175_TGTCCTGGTATCGTAC.1', 'T175_TGTCCTGGTATTCCTT.1'],
      dtype='object', length=16385)

output the renamed files

In [8]:
tumor_list[0]

'T162'

In [9]:
output_path = "../data/Cell/NB_renamed/"
for i in range(len(tumor_list)):
    pd_dataframe_list[i].to_csv(output_path + tumor_list[i] + ".csv", index=False)
    

del pd_dataframe_list
gc.collect()

0

import the renamed files and then horizontally concatenate them by Symbol

In [10]:
input_path = "../data/Cell/NB_renamed/"

files = glob.glob(input_path + "*.csv")
concatenate_list = [pd.read_csv(file, index_col=0) for file in files]
for file in concatenate_list:
    # print(file.head())
    duplicated_list = file[file.index.duplicated(keep=False)].index.to_list()
    duplicated_list = list(set(duplicated_list))  # remove duplicates
    for duplicated_symbol in duplicated_list:
        insert = file.loc[duplicated_symbol].mean()  # calculate the mean expression of duplicated symbols for each cell
        file.drop(duplicated_symbol, axis="index", inplace=True)  # delete the duplicated symbols first
        file.loc[duplicated_symbol] = insert  # insert back the mean
    print(file[file.index.duplicated()])  # check is there duplicated symbols?

Empty DataFrame
Columns: [T44_AAACCTGAGAGGTTGC.1, T44_AAACCTGAGAGTGAGA.1, T44_AAACCTGAGGCATGTG.1, T44_AAACCTGAGTGTACCT.1, T44_AAACCTGCAATGCCAT.1, T44_AAACCTGCAATGGATA.1, T44_AAACCTGCACTGTGTA.1, T44_AAACCTGGTAATCACC.1, T44_AAACCTGGTAGTGAAT.1, T44_AAACCTGGTTGGACCC.1, T44_AAACCTGGTTGTACAC.1, T44_AAACCTGTCAAACGGG.1, T44_AAACCTGTCCGTAGTA.1, T44_AAACGGGAGCCACGCT.1, T44_AAACGGGAGCCCAATT.1, T44_AAACGGGAGTCATCCA.1, T44_AAACGGGAGTGGTAGC.1, T44_AAACGGGCAGATCTGT.1, T44_AAACGGGGTAAATGTG.1, T44_AAACGGGGTAGCGCAA.1, T44_AAACGGGGTGAAATCA.1, T44_AAACGGGTCACTTACT.1, T44_AAACGGGTCCACTGGG.1, T44_AAACGGGTCGAGCCCA.1, T44_AAACGGGTCGTCTGAA.1, T44_AAAGATGAGAGGGCTT.1, T44_AAAGATGAGGATGCGT.1, T44_AAAGATGTCCGCGTTT.1, T44_AAAGATGTCCTTTACA.1, T44_AAAGATGTCGCTTAGA.1, T44_AAAGATGTCTCAACTT.1, T44_AAAGCAAAGCCAGAAC.1, T44_AAAGCAAAGCCAGTTT.1, T44_AAAGCAAAGTGACATA.1, T44_AAAGCAACACTGTGTA.1, T44_AAAGCAACAGGATTGG.1, T44_AAAGCAAGTCGCCATG.1, T44_AAAGCAAGTCGGGTCT.1, T44_AAAGCAAGTTTCGCTC.1, T44_AAAGCAATCATAAAGG.1, T44_AAAGTAGAGACGACGT.1, T44_AAAGTAGAGAGGGCTT.1, T44_AAAGTAGAGCGTCAAG.1, T44_AAAGTAGAGGATTCGG.1, T44_AAAGTAGCAAGCGCTC.1, T44_AAAGTAGCAGAGCCAA.1, T44_AAAGTAGCAGCTGCAC.1, T44_AAAGTAGCAGTTTACG.1, T44_AAAGTAGGTCACACGC.1, T44_AAAGTAGGTCAGGACA.1, T44_AAAGTAGGTCTTGCGG.1, T44_AAAGTAGGTGCAGACA.1, T44_AAAGTAGGTTAAAGTG.1, T44_AAAGTAGGTTGATTGC.1, T44_AAAGTAGTCACAAACC.1, T44_AAAGTAGTCACGCGGT.1, T44_AAAGTAGTCCGTACAA.1, T44_AAAGTAGTCCTGTACC.1, T44_AAAGTAGTCGGAGCAA.1, T44_AAAGTAGTCGTTTAGG.1, T44_AAAGTAGTCGTTTGCC.1, T44_AAAGTAGTCTAACCGA.1, T44_AAAGTAGTCTTACCTA.1, T44_AAATGCCAGATGTAAC.1, T44_AAATGCCAGTGGCACA.1, T44_AAATGCCAGTGTACTC.1, T44_AAATGCCCATCACCCT.1, T44_AAATGCCGTCGAGTTT.1, T44_AAATGCCGTTATGCGT.1, T44_AAATGCCGTTGTCGCG.1, T44_AAATGCCTCGATCCCT.1, T44_AAATGCCTCGTCTGCT.1, T44_AAATGCCTCTATCGCC.1, T44_AACACGTAGAGATGAG.1, T44_AACACGTAGCAGATCG.1, T44_AACACGTAGCCTTGAT.1, T44_AACACGTAGCGCTCCA.1, T44_AACACGTAGCTCCTTC.1, T44_AACACGTAGCTGGAAC.1, T44_AACACGTAGGCGTACA.1, T44_AACACGTCAAAGGAAG.1, T44_AACACGTCAATGTAAG.1, T44_AACACGTCACCGGAAA.1, T44_AACACGTCACTGTGTA.1, T44_AACACGTCAGTAGAGC.1, T44_AACACGTCATTAACCG.1, T44_AACACGTGTGGCTCCA.1, T44_AACACGTGTGTAATGA.1, T44_AACACGTTCCAGAAGG.1, T44_AACACGTTCGTCCAGG.1, T44_AACACGTTCTAAGCCA.1, T44_AACACGTTCTATCCTA.1, T44_AACCATGAGGCTACGA.1, T44_AACCATGAGTCCAGGA.1, T44_AACCATGAGTGGTCCC.1, T44_AACCATGCACGGACAA.1, T44_AACCATGCACTCTGTC.1, T44_AACCATGCAGGACCCT.1, T44_AACCATGCATCACCCT.1, T44_AACCATGGTATAGTAG.1, ...]
Index: []

[0 rows x 6916 columns]
Empty DataFrame
Columns: [T71_AAACCTGAGAAGGACA.1, T71_AAACCTGAGACGCTTT.1, T71_AAACCTGAGATCCGAG.1, T71_AAACCTGAGATGCGAC.1, T71_AAACCTGAGCAGCCTC.1, T71_AAACCTGAGCTCCTCT.1, T71_AAACCTGAGTATTGGA.1, T71_AAACCTGAGTGGTAGC.1, T71_AAACCTGAGTTGCAGG.1, T71_AAACCTGCAACTGCTA.1, T71_AAACCTGCACCTCGTT.1, T71_AAACCTGCACGCCAGT.1, T71_AAACCTGCACGTTGGC.1, T71_AAACCTGGTAAGCACG.1, T71_AAACCTGGTACAGACG.1, T71_AAACCTGGTAGCCTCG.1, T71_AAACCTGGTAGCGATG.1, T71_AAACCTGGTCTTCTCG.1, T71_AAACCTGGTTTCCACC.1, T71_AAACCTGTCAATCACG.1, T71_AAACCTGTCACGAAGG.1, T71_AAACCTGTCAGCACAT.1, T71_AAACCTGTCAGTTCGA.1, T71_AAACCTGTCATGTCTT.1, T71_AAACCTGTCCATGAGT.1, T71_AAACCTGTCCTTTCTC.1, T71_AAACCTGTCGAATGGG.1, T71_AAACCTGTCGGCGGTT.1, T71_AAACCTGTCTTATCTG.1, T71_AAACGGGAGAGGGATA.1, T71_AAACGGGAGCTAAACA.1, T71_AAACGGGAGCTCTCGG.1, T71_AAACGGGAGTCAAGCG.1, T71_AAACGGGCAAGGCTCC.1, T71_AAACGGGCAATGCCAT.1, T71_AAACGGGCACATGTGT.1, T71_AAACGGGCAGATGGGT.1, T71_AAACGGGCAGCTTCGG.1, T71_AAACGGGGTAGGCTGA.1, T71_AAACGGGGTCAAACTC.1, T71_AAACGGGGTCGAGTTT.1, T71_AAACGGGGTCTCTTAT.1, T71_AAACGGGGTGCAGTAG.1, T71_AAACGGGGTTACGGAG.1, T71_AAACGGGGTTGATTCG.1, T71_AAACGGGTCATCTGTT.1, T71_AAACGGGTCATGTCCC.1, T71_AAACGGGTCCGAATGT.1, T71_AAACGGGTCGCTTAGA.1, T71_AAACGGGTCTGCTTGC.1, T71_AAAGATGAGAAGATTC.1, T71_AAAGATGAGAGCTATA.1, T71_AAAGATGAGCAGGCTA.1, T71_AAAGATGAGCTACCTA.1, T71_AAAGATGAGGATGTAT.1, T71_AAAGATGAGGGTGTGT.1, T71_AAAGATGAGTGTGGCA.1, T71_AAAGATGCAAAGCGGT.1, T71_AAAGATGCAAAGTGCG.1, T71_AAAGATGCACCACCAG.1, T71_AAAGATGCACGAGGTA.1, T71_AAAGATGCACTTAACG.1, T71_AAAGATGCATCCTTGC.1, T71_AAAGATGCATGCCCGA.1, T71_AAAGATGCATGGGACA.1, T71_AAAGATGGTAAGGATT.1, T71_AAAGATGGTAGGCTGA.1, T71_AAAGATGGTCCAGTTA.1, T71_AAAGATGGTCTTGCGG.1, T71_AAAGATGGTGCACCAC.1, T71_AAAGATGGTTTAGCTG.1, T71_AAAGATGGTTTGGGCC.1, T71_AAAGATGTCACAATGC.1, T71_AAAGATGTCTCGATGA.1, T71_AAAGATGTCTCTGAGA.1, T71_AAAGATGTCTGGTATG.1, T71_AAAGCAAAGAAGATTC.1, T71_AAAGCAAAGATCACGG.1, T71_AAAGCAAAGGGAACGG.1, T71_AAAGCAAAGGGCACTA.1, T71_AAAGCAAAGTAACCCT.1, T71_AAAGCAACAAACTGCT.1, T71_AAAGCAACAAGCTGTT.1, T71_AAAGCAACACGTAAGG.1, T71_AAAGCAACAGCTCCGA.1, T71_AAAGCAACATAAGACA.1, T71_AAAGCAACATACCATG.1, T71_AAAGCAACATTTCAGG.1, T71_AAAGCAAGTACTTGAC.1, T71_AAAGCAAGTCGCATCG.1, T71_AAAGCAAGTCTTTCAT.1, T71_AAAGCAAGTTACGCGC.1, T71_AAAGCAAGTTATCACG.1, T71_AAAGCAAGTTCCCTTG.1, T71_AAAGCAAGTTCGTGAT.1, T71_AAAGCAAGTTTGGCGC.1, T71_AAAGCAATCATACGGT.1, T71_AAAGCAATCCAAACAC.1, T71_AAAGCAATCCGCAGTG.1, T71_AAAGCAATCGCAAGCC.1, ...]
Index: []

[0 rows x 12471 columns]
Empty DataFrame
Columns: [T162_AAACCCAAGACCATTC.1, T162_AAACCCAAGATCCAAA.1, T162_AAACCCAAGATGAAGG.1, T162_AAACCCAAGCAAACAT.1, T162_AAACCCAAGCACAAAT.1, T162_AAACCCAAGCACTTTG.1, T162_AAACCCAAGCTCCACG.1, T162_AAACCCAAGGCAGGGA.1, T162_AAACCCAAGGCATGGT.1, T162_AAACCCAAGTTCCAGT.1, T162_AAACCCACAAATTGGA.1, T162_AAACCCACAACCCTCT.1, T162_AAACCCACAACGATTC.1, T162_AAACCCACAAGACAAT.1, T162_AAACCCACAAGCCATT.1, T162_AAACCCACAAGGACAC.1, T162_AAACCCACACGCGCTA.1, T162_AAACCCACACTAACGT.1, T162_AAACCCACAGAACGCA.1, T162_AAACCCACAGGCCCTA.1, T162_AAACCCACAGTCTTCC.1, T162_AAACCCACATCCGTGG.1, T162_AAACCCACATCTTTCA.1, T162_AAACCCACATGATAGA.1, T162_AAACCCAGTAAGATCA.1, T162_AAACCCAGTACGTACT.1, T162_AAACCCAGTAGTCGGA.1, T162_AAACCCAGTATTCCGA.1, T162_AAACCCAGTCTACACA.1, T162_AAACCCAGTGATCGTT.1, T162_AAACCCAGTGTGTCCG.1, T162_AAACCCAGTGTTTCTT.1, T162_AAACCCAGTTAGTTCG.1, T162_AAACCCAGTTCAAACC.1, T162_AAACCCAGTTGAGTCT.1, T162_AAACCCATCATCAGTG.1, T162_AAACCCATCATTTCGT.1, T162_AAACCCATCCACGAAT.1, T162_AAACCCATCCATCTGC.1, T162_AAACCCATCCCGAAAT.1, T162_AAACCCATCCCGTAAA.1, T162_AAACCCATCCGTGTCT.1, T162_AAACCCATCGATCCCT.1, T162_AAACCCATCGTTCCCA.1, T162_AAACCCATCTTCGCTG.1, T162_AAACGAAAGCACCTGC.1, T162_AAACGAAAGGACAAGA.1, T162_AAACGAAAGGCAGGTT.1, T162_AAACGAAAGGGCTTCC.1, T162_AAACGAAAGTGTTCAC.1, T162_AAACGAACAAATAAGC.1, T162_AAACGAACAACGATCT.1, T162_AAACGAACAATAGTCC.1, T162_AAACGAACACAGGATG.1, T162_AAACGAACACCCTGTT.1, T162_AAACGAACATCCGGTG.1, T162_AAACGAACATGAGAAT.1, T162_AAACGAAGTACGGTTT.1, T162_AAACGAAGTAGTCGGA.1, T162_AAACGAAGTCCATAGT.1, T162_AAACGAAGTCCTCAGG.1, T162_AAACGAAGTCGCAGTC.1, T162_AAACGAAGTCTGCGCA.1, T162_AAACGAAGTTCCGTTC.1, T162_AAACGAAGTTCGCGTG.1, T162_AAACGAAGTTTAGACC.1, T162_AAACGAATCACCGGTG.1, T162_AAACGAATCCGTAATG.1, T162_AAACGAATCGTTAGTG.1, T162_AAACGAATCTCCAAGA.1, T162_AAACGAATCTCTCTTC.1, T162_AAACGCTAGCACTCAT.1, T162_AAACGCTAGCGTTCAT.1, T162_AAACGCTAGCTAATCC.1, T162_AAACGCTCAAAGAACT.1, T162_AAACGCTCAAAGGCTG.1, T162_AAACGCTCAAAGGGTC.1, T162_AAACGCTCAACAGCCC.1, T162_AAACGCTCAAGGCTTT.1, T162_AAACGCTCACTAACCA.1, T162_AAACGCTCAGGACATG.1, T162_AAACGCTCAGGCATTT.1, T162_AAACGCTCATGGGTTT.1, T162_AAACGCTGTATTGAGA.1, T162_AAACGCTGTCCGTTTC.1, T162_AAACGCTGTCGAACAG.1, T162_AAACGCTGTGATATAG.1, T162_AAACGCTGTGGTACAG.1, T162_AAACGCTGTGGTCTAT.1, T162_AAACGCTGTGTCTTAG.1, T162_AAACGCTGTGTGCCTG.1, T162_AAACGCTGTTCCGCAG.1, T162_AAACGCTTCAAAGAAC.1, T162_AAACGCTTCAAGCCTA.1, T162_AAACGCTTCAAGGCTT.1, T162_AAACGCTTCCAACTAG.1, T162_AAACGCTTCCACGGGT.1, T162_AAACGCTTCGGAATTC.1, T162_AAACGCTTCGTTTACT.1, T162_AAACGCTTCTGCATAG.1, ...]
Index: []

[0 rows x 16384 columns]
Empty DataFrame
Columns: [T92_AAACCTGAGCGTGAAC.1, T92_AAACCTGAGGGATCTG.1, T92_AAACCTGCAAATCCGT.1, T92_AAACCTGCACACCGAC.1, T92_AAACCTGTCAAGAAGT.1, T92_AAACCTGTCTTGTTTG.1, T92_AAACGGGGTGACTCAT.1, T92_AAACGGGTCACCGTAA.1, T92_AAAGATGAGAGGGCTT.1, T92_AAAGATGAGCCCTAAT.1, T92_AAAGATGAGGAATCGC.1, T92_AAAGATGCATCGGTTA.1, T92_AAAGATGGTGCGGTAA.1, T92_AAAGATGGTGTAACGG.1, T92_AAAGATGTCACTATTC.1, T92_AAAGATGTCCTTGGTC.1, T92_AAAGATGTCGAATGGG.1, T92_AAAGCAAAGATCGGGT.1, T92_AAAGCAAAGCCCTAAT.1, T92_AAAGCAAAGCCGTCGT.1, T92_AAAGCAAAGGAGTAGA.1, T92_AAAGCAAAGTGTGAAT.1, T92_AAAGCAACAAGCGCTC.1, T92_AAAGCAACAATAACGA.1, T92_AAAGCAATCCGCAGTG.1, T92_AAAGCAATCGTTGCCT.1, T92_AAAGCAATCTAGCACA.1, T92_AAAGTAGAGGCTCATT.1, T92_AAAGTAGAGGGCACTA.1, T92_AAAGTAGAGTTCGCAT.1, T92_AAAGTAGCAGATCGGA.1, T92_AAAGTAGTCATGTAGC.1, T92_AAAGTAGTCGACCAGC.1, T92_AAATGCCAGAGGGCTT.1, T92_AAATGCCAGATCACGG.1, T92_AAATGCCAGCTTATCG.1, T92_AAATGCCCACGGATAG.1, T92_AAATGCCCATAGACTC.1, T92_AAATGCCGTAGGGTAC.1, T92_AAATGCCTCCTGCTTG.1, T92_AAATGCCTCGCAAACT.1, T92_AAATGCCTCGGACAAG.1, T92_AAATGCCTCTGCGGCA.1, T92_AAATGCCTCTTGTACT.1, T92_AACACGTCAAGCCGCT.1, T92_AACACGTCACGTCAGC.1, T92_AACACGTCACTTGGAT.1, T92_AACACGTCAGCTCCGA.1, T92_AACACGTCAGCTGTTA.1, T92_AACACGTCAGTATGCT.1, T92_AACACGTGTAGCGTCC.1, T92_AACACGTGTCACCTAA.1, T92_AACACGTGTCGTCTTC.1, T92_AACACGTGTGCGCTTG.1, T92_AACACGTTCAGCCTAA.1, T92_AACACGTTCATTATCC.1, T92_AACACGTTCGTTTGCC.1, T92_AACCATGAGAAGGACA.1, T92_AACCATGAGGCATGGT.1, T92_AACCATGAGGGAAACA.1, T92_AACCATGAGTACACCT.1, T92_AACCATGAGTACATGA.1, T92_AACCATGCACACGCTG.1, T92_AACCATGCACAGATTC.1, T92_AACCATGCATATGAGA.1, T92_AACCATGTCTCCCTGA.1, T92_AACCATGTCTTCAACT.1, T92_AACCATGTCTTGTATC.1, T92_AACCGCGCAACCGCCA.1, T92_AACCGCGCAGACACTT.1, T92_AACCGCGCAGACAGGT.1, T92_AACCGCGGTACGCTGC.1, T92_AACCGCGGTGCACTTA.1, T92_AACCGCGGTGGTTTCA.1, T92_AACCGCGTCCGCATCT.1, T92_AACGTTGAGGGAGTAA.1, T92_AACGTTGAGGGCATGT.1, T92_AACGTTGAGTGCGTGA.1, T92_AACGTTGCAAAGAATC.1, T92_AACGTTGCAAGACGTG.1, T92_AACGTTGCAATCTGCA.1, T92_AACGTTGCAGGCTCAC.1, T92_AACGTTGGTAGCGTAG.1, T92_AACGTTGGTCTCACCT.1, T92_AACGTTGGTTAAGATG.1, T92_AACGTTGTCCCAACGG.1, T92_AACTCAGAGAGCTGCA.1, T92_AACTCAGAGCTGTTCA.1, T92_AACTCAGCAAGCCTAT.1, T92_AACTCAGCAGCCTTGG.1, T92_AACTCAGCAGTCACTA.1, T92_AACTCAGCATGGTTGT.1, T92_AACTCAGGTCACACGC.1, T92_AACTCAGGTCCGTTAA.1, T92_AACTCAGGTGTTTGGT.1, T92_AACTCAGGTTGAGTTC.1, T92_AACTCCCAGAATCTCC.1, T92_AACTCCCAGAGTAAGG.1, T92_AACTCCCAGAGTGACC.1, T92_AACTCCCAGGGAACGG.1, ...]
Index: []

[0 rows x 4242 columns]
Empty DataFrame
Columns: [T175_AAACCCAAGAGTGTTA.1, T175_AAACCCAAGCCTGGAA.1, T175_AAACCCAAGCGGACAT.1, T175_AAACCCAAGTCTGTAC.1, T175_AAACCCACACAATGCT.1, T175_AAACCCACACGAGAAC.1, T175_AAACCCACAGCTACCG.1, T175_AAACCCACATCACCAA.1, T175_AAACCCACATCCTATT.1, T175_AAACCCACATTCTCTA.1, T175_AAACCCAGTATGGGAC.1, T175_AAACCCAGTGCTCTTC.1, T175_AAACCCAGTTTCGCTC.1, T175_AAACCCATCCACGTGG.1, T175_AAACCCATCGTCTAAG.1, T175_AAACGAAAGCAGCCCT.1, T175_AAACGAAAGCGATTCT.1, T175_AAACGAAAGGTCGAGT.1, T175_AAACGAACAGAGGGTT.1, T175_AAACGAACATCGGAGA.1, T175_AAACGAAGTACTGAGG.1, T175_AAACGAAGTCATCTAG.1, T175_AAACGAAGTCGCTGCA.1, T175_AAACGAAGTCTGTAGT.1, T175_AAACGAAGTCTTCTAT.1, T175_AAACGAAGTCTTTATC.1, T175_AAACGAAGTGGAGGTT.1, T175_AAACGAAGTGGGTTGA.1, T175_AAACGAAGTTAAGTCC.1, T175_AAACGAAGTTAGGCTT.1, T175_AAACGAAGTTCAGGTT.1, T175_AAACGAATCACTGAAC.1, T175_AAACGAATCAGAGCGA.1, T175_AAACGAATCCACGGGT.1, T175_AAACGAATCCCAACTC.1, T175_AAACGAATCCGTCCTA.1, T175_AAACGAATCCGTGGCA.1, T175_AAACGAATCCTCTCGA.1, T175_AAACGAATCCTGCTAC.1, T175_AAACGAATCGCTTACC.1, T175_AAACGAATCTGATGGT.1, T175_AAACGCTAGTAAACAC.1, T175_AAACGCTCAAATGAAC.1, T175_AAACGCTCAAGAATAC.1, T175_AAACGCTCAAGTCCAT.1, T175_AAACGCTCACCAGGTC.1, T175_AAACGCTCACGGCCAT.1, T175_AAACGCTGTACTGCCG.1, T175_AAACGCTGTAGACACG.1, T175_AAACGCTGTAGGAGTC.1, T175_AAACGCTGTCATTGCA.1, T175_AAACGCTGTCTCAGAT.1, T175_AAACGCTGTGTTGAGG.1, T175_AAACGCTGTTAGGGAC.1, T175_AAACGCTGTTTGGAGG.1, T175_AAACGCTTCCACCTCA.1, T175_AAACGCTTCCGAAATC.1, T175_AAACGCTTCCTCTCGA.1, T175_AAACGCTTCGCATGAT.1, T175_AAACGCTTCGGCATCG.1, T175_AAACGCTTCTGGGAGA.1, T175_AAAGAACAGCCTGGAA.1, T175_AAAGAACAGCTGACAG.1, T175_AAAGAACAGGACTTCT.1, T175_AAAGAACCAAGAGAGA.1, T175_AAAGAACCAAGCGCTC.1, T175_AAAGAACCAAGTAGTA.1, T175_AAAGAACCAATACCTG.1, T175_AAAGAACCACGGGTAA.1, T175_AAAGAACCAGCTAACT.1, T175_AAAGAACCATCCTTCG.1, T175_AAAGAACGTCATCCGG.1, T175_AAAGAACGTCCTATAG.1, T175_AAAGAACGTCCTCCAT.1, T175_AAAGAACGTCGTTGCG.1, T175_AAAGAACTCCCGTGAG.1, T175_AAAGAACTCGCTCTAC.1, T175_AAAGGATAGAAGCTGC.1, T175_AAAGGATAGACTGTTC.1, T175_AAAGGATAGTATGCAA.1, T175_AAAGGATAGTTGGCGA.1, T175_AAAGGATCAACGAGGT.1, T175_AAAGGATCAACTGATC.1, T175_AAAGGATCAAGAGTAT.1, T175_AAAGGATCAATCACGT.1, T175_AAAGGATCACAAATAG.1, T175_AAAGGATCAGAGCTAG.1, T175_AAAGGATCAGTCCCGA.1, T175_AAAGGATCATCGATCA.1, T175_AAAGGATGTGGCTTAT.1, T175_AAAGGATGTTGCGTAT.1, T175_AAAGGATTCAAGTAAG.1, T175_AAAGGATTCCATAGAC.1, T175_AAAGGATTCGTCTCAC.1, T175_AAAGGATTCTAGTGAC.1, T175_AAAGGGCAGAGTAACT.1, T175_AAAGGGCAGATGCAGC.1, T175_AAAGGGCAGCCTGCCA.1, T175_AAAGGGCAGGCGTTAG.1, T175_AAAGGGCAGGTAAAGG.1, ...]
Index: []

[0 rows x 16384 columns]
Empty DataFrame
Columns: [T214_AAACCCAAGAAGTCTA.1, T214_AAACCCAAGCAACTTC.1, T214_AAACCCAAGCCGTAAG.1, T214_AAACCCAAGCTAGAGC.1, T214_AAACCCAAGCTGCCTG.1, T214_AAACCCAAGGGATCGT.1, T214_AAACCCACAACCTAAC.1, T214_AAACCCACAAGTGATA.1, T214_AAACCCAGTAGACGGT.1, T214_AAACCCAGTATGGTTC.1, T214_AAACCCAGTGCAGTGA.1, T214_AAACCCATCCTCTCTT.1, T214_AAACCCATCCTGTACC.1, T214_AAACGAAAGAGGGTCT.1, T214_AAACGAAAGTGTTGTC.1, T214_AAACGAAGTCTGCCTT.1, T214_AAACGAATCACCATAG.1, T214_AAACGAATCTAATTCC.1, T214_AAACGCTCAAGGGTCA.1, T214_AAACGCTCAAGTTCCA.1, T214_AAACGCTCACAACATC.1, T214_AAACGCTCAGCGACCT.1, T214_AAACGCTGTCACTGAT.1, T214_AAACGCTGTCGTACAT.1, T214_AAACGCTGTCTAGGTT.1, T214_AAACGCTTCAGCACCG.1, T214_AAACGCTTCAGGAAAT.1, T214_AAACGCTTCGGCATAT.1, T214_AAAGAACAGCCGTCGT.1, T214_AAAGAACAGTTGCTCA.1, T214_AAAGAACGTTAACCTG.1, T214_AAAGAACGTTATGACC.1, T214_AAAGAACTCACCCTTG.1, T214_AAAGAACTCTACTTCA.1, T214_AAAGAACTCTAGTACG.1, T214_AAAGAACTCTCCGTGT.1, T214_AAAGGATAGGTCGTCC.1, T214_AAAGGATCAATACCTG.1, T214_AAAGGATCAGAAGCGT.1, T214_AAAGGATGTATGAAAC.1, T214_AAAGGATGTCGGATTT.1, T214_AAAGGATGTGAGTAGC.1, T214_AAAGGATGTGATACAA.1, T214_AAAGGATGTGTCCATA.1, T214_AAAGGATTCCACTGAA.1, T214_AAAGGATTCCATCGTC.1, T214_AAAGGATTCTGGCTGG.1, T214_AAAGGATTCTTTCGAT.1, T214_AAAGGGCAGATGCTAA.1, T214_AAAGGGCAGCGGTATG.1, T214_AAAGGGCAGGGTATAT.1, T214_AAAGGGCCACACCGAC.1, T214_AAAGGGCCACTTCATT.1, T214_AAAGGGCCAGCGTTGC.1, T214_AAAGGGCCATAACCCA.1, T214_AAAGGGCGTATGGAGC.1, T214_AAAGGGCGTATTGGCT.1, T214_AAAGGGCGTCCTTAAG.1, T214_AAAGGGCGTCTCGACG.1, T214_AAAGGGCGTGCCCGTA.1, T214_AAAGGGCGTGTTCATG.1, T214_AAAGGGCGTTCAGCGC.1, T214_AAAGGGCTCAGAACCT.1, T214_AAAGGGCTCAGTGTTG.1, T214_AAAGGGCTCCTGTAGA.1, T214_AAAGGTAAGAAGTCTA.1, T214_AAAGGTAAGAATACAC.1, T214_AAAGGTAAGATGTAGT.1, T214_AAAGGTAAGCGATGAC.1, T214_AAAGGTACAAGCGCTC.1, T214_AAAGGTACACAAGTTC.1, T214_AAAGGTACACGTGAGA.1, T214_AAAGGTACAGTCGCTG.1, T214_AAAGGTAGTCCTCCAT.1, T214_AAAGGTAGTCTTGCGG.1, T214_AAAGGTATCCGGCAGT.1, T214_AAAGGTATCCTAAACG.1, T214_AAAGGTATCGCCAGAC.1, T214_AAAGGTATCGCCGTGA.1, T214_AAAGTCCAGGCGACAT.1, T214_AAAGTCCAGTAACCGG.1, T214_AAAGTCCCAATCCTTT.1, T214_AAAGTCCCACCCTGTT.1, T214_AAAGTCCCAGGACGAT.1, T214_AAAGTCCCATACCATG.1, T214_AAAGTCCGTTCATCGA.1, T214_AAAGTCCGTTGTCTAG.1, T214_AAAGTCCTCACGGGAA.1, T214_AAAGTCCTCACTGGGC.1, T214_AAAGTCCTCCTGATAG.1, T214_AAAGTCCTCGCAACAT.1, T214_AAAGTGAAGTATGACA.1, T214_AAAGTGACAGTGTGCC.1, T214_AAAGTGAGTTATCTTC.1, T214_AAAGTGATCGTAGGGA.1, T214_AAAGTGATCGTTAGAC.1, T214_AAATGGAAGCTGCCAC.1, T214_AAATGGAAGTACCCTA.1, T214_AAATGGAAGTAGCCAG.1, T214_AAATGGAAGTCATGCT.1, ...]
Index: []

[0 rows x 10347 columns]
Empty DataFrame
Columns: [T230_AAACCCAAGAACCGCA.1, T230_AAACCCAAGACGAGCT.1, T230_AAACCCACAATACCCA.1, T230_AAACCCACACAGTACT.1, T230_AAACCCACACTGAATC.1, T230_AAACCCACAGATACCT.1, T230_AAACCCACAGTTGAAA.1, T230_AAACCCAGTAGTCTTG.1, T230_AAACCCAGTCTACGTA.1, T230_AAACCCAGTCTTTCAT.1, T230_AAACCCATCGGTAAGG.1, T230_AAACGAAAGAGATGCC.1, T230_AAACGAAAGATACATG.1, T230_AAACGAAAGGAGGGTG.1, T230_AAACGAAAGGCACTAG.1, T230_AAACGAACAAGCGAGT.1, T230_AAACGAACAATGCAAA.1, T230_AAACGAACATTCACCC.1, T230_AAACGAAGTATCAGGG.1, T230_AAACGAAGTTCCGCAG.1, T230_AAACGAAGTTGTGTTG.1, T230_AAACGAAGTTTCGTTT.1, T230_AAACGAATCACGATCA.1, T230_AAACGAATCATAGCAC.1, T230_AAACGAATCCCAGGCA.1, T230_AAACGAATCTTGGAAC.1, T230_AAACGCTAGAATCGAT.1, T230_AAACGCTAGATGTTAG.1, T230_AAACGCTAGATTGGGC.1, T230_AAACGCTAGTTACGTC.1, T230_AAACGCTCAATGCTCA.1, T230_AAACGCTCACATTACG.1, T230_AAACGCTGTAAGGCTG.1, T230_AAACGCTGTATCCCTC.1, T230_AAACGCTGTCTCACAA.1, T230_AAACGCTGTCTTACTT.1, T230_AAACGCTTCTCCGATC.1, T230_AAACGCTTCTTTCTAG.1, T230_AAAGAACCACCCAAGC.1, T230_AAAGAACCAGGACAGT.1, T230_AAAGAACCAGTAGGAC.1, T230_AAAGAACCATGTGCTA.1, T230_AAAGAACGTCACTGAT.1, T230_AAAGAACGTCTGGTTA.1, T230_AAAGAACGTTAACAGA.1, T230_AAAGAACTCGACATCA.1, T230_AAAGAACTCTGTCCCA.1, T230_AAAGGATAGAAGGATG.1, T230_AAAGGATAGAGAGTTT.1, T230_AAAGGATAGAGGGTCT.1, T230_AAAGGATAGATTGCGG.1, T230_AAAGGATAGCATTTGC.1, T230_AAAGGATAGCTAGATA.1, T230_AAAGGATAGCTCTGTA.1, T230_AAAGGATAGGATCACG.1, T230_AAAGGATAGTCCCGGT.1, T230_AAAGGATCATGACTGT.1, T230_AAAGGATGTAACCCTA.1, T230_AAAGGATGTAGCTTTG.1, T230_AAAGGATGTCACCCTT.1, T230_AAAGGATGTGAGCCAA.1, T230_AAAGGATGTTCCGCTT.1, T230_AAAGGATTCAACTACG.1, T230_AAAGGATTCACCTCGT.1, T230_AAAGGATTCCATGCAA.1, T230_AAAGGATTCCGTGGTG.1, T230_AAAGGATTCTGTCGCT.1, T230_AAAGGGCAGACTAAGT.1, T230_AAAGGGCAGCCTCTTC.1, T230_AAAGGGCAGGATGGCT.1, T230_AAAGGGCAGTTTCGAC.1, T230_AAAGGGCCAAACCACT.1, T230_AAAGGGCCAAAGTGTA.1, T230_AAAGGGCCATTAGGAA.1, T230_AAAGGGCGTCTACACA.1, T230_AAAGGGCGTCTCAGGC.1, T230_AAAGGGCGTGGAACCA.1, T230_AAAGGGCTCACCTACC.1, T230_AAAGGGCTCATGCAGT.1, T230_AAAGGGCTCATGTCTT.1, T230_AAAGGGCTCCCTGTTG.1, T230_AAAGGGCTCCGACAGC.1, T230_AAAGGGCTCTACTATC.1, T230_AAAGGGCTCTCAGAAC.1, T230_AAAGGGCTCTGTGTGA.1, T230_AAAGGGCTCTTCTGGC.1, T230_AAAGGTAAGCCATCCG.1, T230_AAAGGTAAGCGGGTAT.1, T230_AAAGGTAAGTAGCCAG.1, T230_AAAGGTACAGATACCT.1, T230_AAAGGTACAGCAGGAT.1, T230_AAAGGTACAGCATTGT.1, T230_AAAGGTACAGGGCTTC.1, T230_AAAGGTACAGTGACCC.1, T230_AAAGGTACATTCCTAT.1, T230_AAAGGTAGTATCAGGG.1, T230_AAAGGTAGTCCATCTC.1, T230_AAAGGTAGTGTTGCCG.1, T230_AAAGGTATCCGTGGGT.1, T230_AAAGGTATCGCGATCG.1, ...]
Index: []

[0 rows x 14529 columns]
Empty DataFrame

In [11]:
horizontally_concatenated_csv_file = pd.concat(concatenate_list, axis=1, join="inner")
horizontally_concatenated_csv_file.head()


del files
del concatenate_list
del duplicated_list
gc.collect()

0

In [12]:
output_path = "../data/Cell/"
# save file
horizontally_concatenated_csv_file.to_csv(output_path + "concatenated.csv")

transpose the concatenated file

In [13]:
# horizontally_concatenated_csv_file = pd.read_csv("/hdd/edward/the-project/data/GSE137804_RAW/Patient-derived-biopsy-tissues/csv-concatenated/concatenated.csv")
# print(horizontally_concatenated_csv_file.head())
transposed = horizontally_concatenated_csv_file.T
transposed.head()

Symbol,TSPAN6,DPM1,SCYL3,C1orf112,FGR,FUCA2,GCLC,NFYA,STPG1,NIPAL3,...,SEPSECS-AS1,LINC01144,ADORA3,BISPR,PRNCR1,LINC01481,CYB561D2,CCDC7,MATR3,RGS5
T44_AAACCTGAGAGGTTGC.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0
T44_AAACCTGAGAGTGAGA.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,3.5
T44_AAACCTGAGGCATGTG.1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,4.0
T44_AAACCTGAGTGTACCT.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,5.5
T44_AAACCTGCAATGCCAT.1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0

In [14]:
output_path = "../data/Cell/"

print(transposed.columns[:5])
print(transposed.index[:5])
transposed.to_csv(output_path + "transposed.csv")


del horizontally_concatenated_csv_file
gc.collect()

Index(['TSPAN6', 'DPM1', 'SCYL3', 'C1orf112', 'FGR'], dtype='object', name='Symbol')
Index(['T44_AAACCTGAGAGGTTGC.1', 'T44_AAACCTGAGAGTGAGA.1',
       'T44_AAACCTGAGGCATGTG.1', 'T44_AAACCTGAGTGTACCT.1',
       'T44_AAACCTGCAATGCCAT.1'],
      dtype='object')

8

check whether the data is good, remove duplicates, NA

In [15]:
transposed[transposed.index.duplicated()]

Empty DataFrame
Columns: [TSPAN6, DPM1, SCYL3, C1orf112, FGR, FUCA2, GCLC, NFYA, STPG1, NIPAL3, LAS1L, ENPP4, ANKIB1, CYP51A1, KRIT1, RAD52, BAD, LAP3, CD99, HS3ST1, HECW1, MAD1L1, LASP1, SNX11, TMEM176A, M6PR, KLHL13, ICA1, DBNDD1, ALS2, CASP10, CFLAR, NDUFAF7, RBM5, MTMR7, ARF5, SARM1, POLDIP2, PLXND1, AK2, CD38, FKBP4, KDM1A, RBM6, CAMKK1, RECQL, VPS50, HSPB6, ARHGAP33, NDUFAB1, PDK4, ZMYND10, SLC25A13, ST7, CDC27, SLC4A1, HCCS, DVL2, UPF1, SKAP2, SLC25A5, POLR2J, DHX33, THSD7A, LIG3, RPAP3, ACSM3, CIAPIN1, SPPL2B, FAM214B, COPZ2, PRKAR2B, MSL3, CREBBP, GCFC2, WDR54, CROT, ABCB4, KMT2E, RHBDD2, IBTK, ZNF195, MYCBP2, FBXL3, ITGAL, PDK2, ITGA3, ZFX, LAMP2, ITGA2B, GDE1, OSBPL7, TMEM98, MAP3K14, TMEM132A, AP2B1, ZNF263, CX3CL1, SPATA20, CACNA1G, ...]
Index: []

[0 rows x 12939 columns]

In [16]:
transposed.T[transposed.T.index.duplicated()]

Empty DataFrame
Columns: [T44_AAACCTGAGAGGTTGC.1, T44_AAACCTGAGAGTGAGA.1, T44_AAACCTGAGGCATGTG.1, T44_AAACCTGAGTGTACCT.1, T44_AAACCTGCAATGCCAT.1, T44_AAACCTGCAATGGATA.1, T44_AAACCTGCACTGTGTA.1, T44_AAACCTGGTAATCACC.1, T44_AAACCTGGTAGTGAAT.1, T44_AAACCTGGTTGGACCC.1, T44_AAACCTGGTTGTACAC.1, T44_AAACCTGTCAAACGGG.1, T44_AAACCTGTCCGTAGTA.1, T44_AAACGGGAGCCACGCT.1, T44_AAACGGGAGCCCAATT.1, T44_AAACGGGAGTCATCCA.1, T44_AAACGGGAGTGGTAGC.1, T44_AAACGGGCAGATCTGT.1, T44_AAACGGGGTAAATGTG.1, T44_AAACGGGGTAGCGCAA.1, T44_AAACGGGGTGAAATCA.1, T44_AAACGGGTCACTTACT.1, T44_AAACGGGTCCACTGGG.1, T44_AAACGGGTCGAGCCCA.1, T44_AAACGGGTCGTCTGAA.1, T44_AAAGATGAGAGGGCTT.1, T44_AAAGATGAGGATGCGT.1, T44_AAAGATGTCCGCGTTT.1, T44_AAAGATGTCCTTTACA.1, T44_AAAGATGTCGCTTAGA.1, T44_AAAGATGTCTCAACTT.1, T44_AAAGCAAAGCCAGAAC.1, T44_AAAGCAAAGCCAGTTT.1, T44_AAAGCAAAGTGACATA.1, T44_AAAGCAACACTGTGTA.1, T44_AAAGCAACAGGATTGG.1, T44_AAAGCAAGTCGCCATG.1, T44_AAAGCAAGTCGGGTCT.1, T44_AAAGCAAGTTTCGCTC.1, T44_AAAGCAATCATAAAGG.1, T44_AAAGTAGAGACGACGT.1, T44_AAAGTAGAGAGGGCTT.1, T44_AAAGTAGAGCGTCAAG.1, T44_AAAGTAGAGGATTCGG.1, T44_AAAGTAGCAAGCGCTC.1, T44_AAAGTAGCAGAGCCAA.1, T44_AAAGTAGCAGCTGCAC.1, T44_AAAGTAGCAGTTTACG.1, T44_AAAGTAGGTCACACGC.1, T44_AAAGTAGGTCAGGACA.1, T44_AAAGTAGGTCTTGCGG.1, T44_AAAGTAGGTGCAGACA.1, T44_AAAGTAGGTTAAAGTG.1, T44_AAAGTAGGTTGATTGC.1, T44_AAAGTAGTCACAAACC.1, T44_AAAGTAGTCACGCGGT.1, T44_AAAGTAGTCCGTACAA.1, T44_AAAGTAGTCCTGTACC.1, T44_AAAGTAGTCGGAGCAA.1, T44_AAAGTAGTCGTTTAGG.1, T44_AAAGTAGTCGTTTGCC.1, T44_AAAGTAGTCTAACCGA.1, T44_AAAGTAGTCTTACCTA.1, T44_AAATGCCAGATGTAAC.1, T44_AAATGCCAGTGGCACA.1, T44_AAATGCCAGTGTACTC.1, T44_AAATGCCCATCACCCT.1, T44_AAATGCCGTCGAGTTT.1, T44_AAATGCCGTTATGCGT.1, T44_AAATGCCGTTGTCGCG.1, T44_AAATGCCTCGATCCCT.1, T44_AAATGCCTCGTCTGCT.1, T44_AAATGCCTCTATCGCC.1, T44_AACACGTAGAGATGAG.1, T44_AACACGTAGCAGATCG.1, T44_AACACGTAGCCTTGAT.1, T44_AACACGTAGCGCTCCA.1, T44_AACACGTAGCTCCTTC.1, T44_AACACGTAGCTGGAAC.1, T44_AACACGTAGGCGTACA.1, T44_AACACGTCAAAGGAAG.1, T44_AACACGTCAATGTAAG.1, T44_AACACGTCACCGGAAA.1, T44_AACACGTCACTGTGTA.1, T44_AACACGTCAGTAGAGC.1, T44_AACACGTCATTAACCG.1, T44_AACACGTGTGGCTCCA.1, T44_AACACGTGTGTAATGA.1, T44_AACACGTTCCAGAAGG.1, T44_AACACGTTCGTCCAGG.1, T44_AACACGTTCTAAGCCA.1, T44_AACACGTTCTATCCTA.1, T44_AACCATGAGGCTACGA.1, T44_AACCATGAGTCCAGGA.1, T44_AACCATGAGTGGTCCC.1, T44_AACCATGCACGGACAA.1, T44_AACCATGCACTCTGTC.1, T44_AACCATGCAGGACCCT.1, T44_AACCATGCATCACCCT.1, T44_AACCATGGTATAGTAG.1, ...]
Index: []

[0 rows x 157938 columns]

In [17]:
set(transposed.dtypes)

{dtype('float64')}

In [18]:
transposed.isna().sum()

Symbol
TSPAN6       6
DPM1         6
SCYL3        6
C1orf112     6
FGR          6
            ..
LINC01481    6
CYB561D2     6
CCDC7        6
MATR3        6
RGS5         6
Length: 12939, dtype: int64

In [19]:
transposed.isnull().any()

Symbol
TSPAN6       True
DPM1         True
SCYL3        True
C1orf112     True
FGR          True
             ...
LINC01481    True
CYB561D2     True
CCDC7        True
MATR3        True
RGS5         True
Length: 12939, dtype: bool

In [20]:
transposed.isnull().values.any()

True

In [21]:
transposed.dropna(inplace=True)
transposed

Symbol,TSPAN6,DPM1,SCYL3,C1orf112,FGR,FUCA2,GCLC,NFYA,STPG1,NIPAL3,...,SEPSECS-AS1,LINC01144,ADORA3,BISPR,PRNCR1,LINC01481,CYB561D2,CCDC7,MATR3,RGS5
T44_AAACCTGAGAGGTTGC.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0
T44_AAACCTGAGAGTGAGA.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,3.5
T44_AAACCTGAGGCATGTG.1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,4.0
T44_AAACCTGAGTGTACCT.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,5.5
T44_AAACCTGCAATGCCAT.1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
T40_TTTGTCAGTGTCCTCT.1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.5
T40_TTTGTCATCACTTATC.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,16.0
T40_TTTGTCATCAGGCCCA.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
T40_TTTGTCATCTGCAGTA.1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0
T40_TTTGTCATCTGGAGCC.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5

In [22]:
transposed.isnull().values.any()

False

In [23]:
output_path = "../data/Cell/"

print(transposed.columns[:5])
print(transposed.index[:5])
transposed.to_csv(output_path + "cleaned.csv")


del transposed
gc.collect()

Index(['TSPAN6', 'DPM1', 'SCYL3', 'C1orf112', 'FGR'], dtype='object', name='Symbol')
Index(['T44_AAACCTGAGAGGTTGC.1', 'T44_AAACCTGAGAGTGAGA.1',
       'T44_AAACCTGAGGCATGTG.1', 'T44_AAACCTGAGTGTACCT.1',
       'T44_AAACCTGCAATGCCAT.1'],
      dtype='object')

10

transfer to anndata

In [24]:
import anndata as ad
import pandas as pd

pre_anndata = pd.read_csv("../data/Cell/cleaned.csv", index_col=0)
# pre_anndata = transposed
pre_anndata

,TSPAN6,DPM1,SCYL3,C1orf112,FGR,FUCA2,GCLC,NFYA,STPG1,NIPAL3,...,SEPSECS-AS1,LINC01144,ADORA3,BISPR,PRNCR1,LINC01481,CYB561D2,CCDC7,MATR3,RGS5
T44_AAACCTGAGAGGTTGC.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0
T44_AAACCTGAGAGTGAGA.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,3.5
T44_AAACCTGAGGCATGTG.1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,4.0
T44_AAACCTGAGTGTACCT.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,5.5
T44_AAACCTGCAATGCCAT.1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
T40_TTTGTCAGTGTCCTCT.1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.5
T40_TTTGTCATCACTTATC.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,16.0
T40_TTTGTCATCAGGCCCA.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
T40_TTTGTCATCTGCAGTA.1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0
T40_TTTGTCATCTGGAGCC.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5

In [25]:
# pre_anndata.set_index("Symbol", inplace=True)
pre_anndata.rename_axis("Cell_barcode", inplace=True)
pre_anndata.rename_axis("Symbol", axis="columns", inplace=True)
pre_anndata.head()

Symbol,TSPAN6,DPM1,SCYL3,C1orf112,FGR,FUCA2,GCLC,NFYA,STPG1,NIPAL3,...,SEPSECS-AS1,LINC01144,ADORA3,BISPR,PRNCR1,LINC01481,CYB561D2,CCDC7,MATR3,RGS5
Cell_barcode,,,,,,,,,,,,,,,,,,,,,
T44_AAACCTGAGAGGTTGC.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0
T44_AAACCTGAGAGTGAGA.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,3.5
T44_AAACCTGAGGCATGTG.1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,4.0
T44_AAACCTGAGTGTACCT.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,5.5
T44_AAACCTGCAATGCCAT.1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0

output the anndata object to a hdf5 file

In [26]:
adata = ad.AnnData(pre_anndata)
adata

del pre_anndata
gc.collect()

0

In [27]:
output_path = "../data/Cell/"
adata.write(output_path + "counts.h5ad")