In [4]:
%pwd
%cd /home/jovyan/work/COVID/results
%pwd

/home/jovyan/work/COVID/results

'/home/jovyan/work/COVID/results'

In [5]:
import scanpy as sc
import pandas as pd
import numpy as np

In [6]:
adata = sc.read_h5ad("../COVID_all_scVI.h5ad")
adata = adata[adata.obs["cell_type"]=="MoAM"]

In [10]:
adata.uns['log1p']["base"] = None

In [11]:
# Obtain cluster-specific differentially expressed genes
sc.tl.rank_genes_groups(adata, groupby="CoVID-19 severity", layer='scvi_log', groups=['mild/moderate'], reference='control', method="wilcoxon")

In [12]:
deg_mild_ctrl = sc.get.rank_genes_groups_df(adata, group='mild/moderate')
deg_mild_ctrl

            names     scores  logfoldchanges  pvals  pvals_adj
0          TRIM34  38.864994        4.541738    0.0        0.0
1      ST6GALNAC2  38.864994        4.098063    0.0        0.0
2         TNFSF13  38.864994        5.400968    0.0        0.0
3            GET4  38.864994        3.929323    0.0        0.0
4           HMGN4  38.864994        4.243010    0.0        0.0
...           ...        ...             ...    ...        ...
26566  AC106707.1 -38.864861       -3.420083    0.0        0.0
26567     NDUFA11 -38.864994       -3.356690    0.0        0.0
26568      NDUFB8 -38.864994       -3.694486    0.0        0.0
26569      TMBIM4 -38.864994       -2.604525    0.0        0.0
26570       PHKG1 -38.864994       -3.850207    0.0        0.0

[26571 rows x 5 columns]

In [13]:
deg_mild_ctrl.to_csv("deg_mild_ctrl.csv")

In [14]:
# Obtain cluster-specific differentially expressed genes
sc.tl.rank_genes_groups(adata, groupby="CoVID-19 severity", layer='scvi_log', groups=['severe/critical'], reference='control', method="wilcoxon")
deg_severe_ctrl = sc.get.rank_genes_groups_df(adata, group='severe/critical')
deg_severe_ctrl.to_csv("deg_severe_ctrl.csv")
deg_severe_ctrl

            names     scores  logfoldchanges  pvals  pvals_adj
0           HMGN4  46.857437        3.886965    0.0        0.0
1          MRPS24  46.851013        3.946055    0.0        0.0
2            NAPA  46.849182        1.964193    0.0        0.0
3      AC009779.3  46.845001        3.049705    0.0        0.0
4      ST6GALNAC2  46.843750        3.904874    0.0        0.0
...           ...        ...             ...    ...        ...
26566  AC106707.1 -46.844776       -4.627563    0.0        0.0
26567  AC116563.1 -46.846706       -5.215076    0.0        0.0
26568     C1orf56 -46.848328       -5.018399    0.0        0.0
26569       PHKG1 -46.857380       -4.743586    0.0        0.0
26570  AL133453.1 -46.857513       -4.929738    0.0        0.0

[26571 rows x 5 columns]

In [15]:
# Obtain cluster-specific differentially expressed genes
sc.tl.rank_genes_groups(adata, groupby="CoVID-19 severity", layer='scvi_log', groups=['severe/critical'], reference='mild/moderate', method="wilcoxon")
deg_severe_mild = sc.get.rank_genes_groups_df(adata, group='severe/critical')
deg_severe_mild.to_csv("deg_severe_mild.csv")
deg_severe_mild

            names     scores  logfoldchanges  pvals  pvals_adj
0            KLF9  66.681938        2.293320    0.0        0.0
1           NETO2  65.769951        2.060730    0.0        0.0
2           TIMP1  65.420311        2.472326    0.0        0.0
3      AC123595.1  65.346252        2.269227    0.0        0.0
4           ERO1A  65.215645        1.428796    0.0        0.0
...           ...        ...             ...    ...        ...
26566       PRR15 -64.454140       -2.473040    0.0        0.0
26567         NDN -65.129837       -2.421836    0.0        0.0
26568       RAB8A -65.543610       -1.429098    0.0        0.0
26569       EDA2R -65.571304       -3.373713    0.0        0.0
26570   LINC01914 -66.714905       -4.449023    0.0        0.0

[26571 rows x 5 columns]